import React from "react";
import { Sparkles, Eye, Download, Info } from "lucide-react";

export default function DesignBlueprint() {
  return (
    <div className="design-blueprint-view" style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
      
      {/* Design System Card */}
      <div className="dashboard-card" style={{ padding: "24px" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: "16px", marginBottom: "20px" }}>
          <div>
            <h2 style={{ fontSize: "1.25rem", fontWeight: 700, color: "var(--text-main)", display: "flex", alignItems: "center", gap: "8px" }}>
              <Sparkles size={20} style={{ color: "#a78bfa" }} />
              AI Design Blueprint & UI Reference
            </h2>
            <p style={{ fontSize: "0.875rem", color: "var(--text-muted)", marginTop: "4px" }}>
              Visual reference generated by AI for ClientFlow CRM's production interface.
            </p>
          </div>
          <div style={{ display: "flex", gap: "10px" }}>
            <a 
              href="/clientflow_crm_reference.png" 
              target="_blank" 
              rel="noopener noreferrer" 
              className="btn btn-secondary btn-sm"
              style={{ display: "flex", alignItems: "center", gap: "6px" }}
            >
              <Eye size={14} />
              Open Original
            </a>
            <a 
              href="/clientflow_crm_reference.png" 
              download="clientflow_crm_reference.png" 
              className="btn btn-primary btn-sm"
              style={{ display: "flex", alignItems: "center", gap: "6px" }}
            >
              <Download size={14} />
              Download Mockup
            </a>
          </div>
        </div>

        {/* Blueprint Overview Info Alert */}
        <div 
          style={{ 
            padding: "16px", 
            borderRadius: "var(--radius-sm)", 
            backgroundColor: "var(--primary-light)", 
            border: "1px solid rgba(99, 102, 241, 0.2)",
            color: "var(--primary-color)",
            fontSize: "0.85rem",
            display: "flex",
            gap: "12px",
            alignItems: "flex-start",
            marginBottom: "24px"
          }}
        >
          <Info size={18} style={{ flexShrink: 0, marginTop: "2px" }} />
          <div>
            <strong style={{ display: "block", marginBottom: "4px" }}>About this Reference Mockup</strong>
            This conceptual UI mockup represents the target dark-mode visual theme of ClientFlow CRM. It highlights a glassmorphism dashboard UI with key-metric cards, clean data visualizations, activity timelines, and the built-in AI Insights chat assistant panel on the right.
          </div>
        </div>

        {/* Mockup Image Display */}
        <div 
          style={{ 
            position: "relative",
            width: "100%",
            borderRadius: "var(--radius-md)",
            border: "1px solid var(--border-color)",
            overflow: "hidden",
            backgroundColor: "#0d0e12",
            boxShadow: "0 10px 30px rgba(0, 0, 0, 0.3)",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            padding: "12px"
          }}
        >
          <img 
            src="/clientflow_crm_reference.png" 
            alt="ClientFlow CRM AI Dashboard Mockup" 
            style={{ 
              maxWidth: "100%", 
              maxHeight: "680px", 
              objectFit: "contain",
              borderRadius: "var(--radius-sm)",
              display: "block"
            }} 
          />
        </div>
      </div>

      {/* Design System Specifications Details Grid */}
      <div 
        style={{ 
          display: "grid", 
          gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", 
          gap: "24px" 
        }}
      >
        <div className="dashboard-card" style={{ padding: "20px" }}>
          <h3 style={{ fontSize: "1rem", fontWeight: 700, marginBottom: "12px", color: "var(--text-main)" }}>
            Aesthetic System Guidelines
          </h3>
          <ul style={{ paddingLeft: "18px", fontSize: "0.85rem", color: "var(--text-muted)", display: "flex", flexDirection: "column", gap: "10px" }}>
            <li>
              <strong>Primary Color Scheme:</strong> Dark mode base utilizing Deep Slate (#0d0e12) and Night Blue (#1e293b) surfaces combined with glowing neon accents.
            </li>
            <li>
              <strong>Typography:</strong> Modern geometric sans-serif (e.g. Inter, Outfit, or system default) to maximize legibility of customer records and sales parameters.
            </li>
            <li>
              <strong>Cards Design:</strong> Glassmorphism styling with semi-transparent background fills and fine 1px borders to establish depth and focus.
            </li>
          </ul>
        </div>

        <div className="dashboard-card" style={{ padding: "20px" }}>
          <h3 style={{ fontSize: "1rem", fontWeight: 700, marginBottom: "12px", color: "var(--text-main)" }}>
            Visual Elements in the Reference
          </h3>
          <ul style={{ paddingLeft: "18px", fontSize: "0.85rem", color: "var(--text-muted)", display: "flex", flexDirection: "column", gap: "10px" }}>
            <li>
              <strong>CRM Core Metrics:</strong> Highlights active deal opportunity volumes, lead metrics, and monthly CRM revenue closed details.
            </li>
            <li>
              <strong>Lead-to-Customer Funnel:</strong> Clean sales pipeline charts and conversion indicators representing stage movements.
            </li>
            <li>
              <strong>CRM Insights AI Assistant:</strong> A persistent sidebar conversational chat engine evaluating CRM records dynamically.
            </li>
          </ul>
        </div>
      </div>

    </div>
  );
}
